# -*- coding: utf-8 -*-
"""frozensetass1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r4xsZ3TzLjlDTW4Bji25ceeWv-04BSSo
"""

A = frozenset([1, 2, 3, 4])
B = frozenset([3, 4, 5, 6])

# copying a frozenset
C = A.copy()
print(C)

# union
print(A.union(B))

# intersection
print(A.intersection(B))

# difference
print(A.difference(B))

# symmetric_difference
print(A.symmetric_difference(B))

C = frozenset([5, 6])



# isdisjoint() method
print(A.isdisjoint(C))

# issubset() method
print(C.issubset(B))

# issuperset() method
print(B.issuperset(C))

